version: '3.8'

services:
  backend:
    # build: ./backend
    image: aaron2905/sentiment-app-backend:latest
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET="solidpassword"
      - DATABASE_URL=sqlite:///app/database.sqlite
    volumes:
      - backend-data:/app/data
    depends_on:
      - db

  frontend:
    # build: ./frontend
    image: aaron2905/sentiment-app-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3
    volumes:
      - db-data:/root

volumes:
  backend-data:
  db-data:
